name: Resume
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown to PDF and HTML
        uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_dir: resume
          output_dir: artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: artifact
